import Carousal from "./components/Carousal/Carousal";
import Hero from "./components/Hero/Hero";
import Slider from "./components/Slider/Slider";
import Testimonial from "./components/Testimonial/Testimonial"
export default function Home() {
  return (
    <>
      <Carousal />
      <Hero />
      <Slider />
      <Testimonial />
    </>
  );
}

export const generateMetadata = () => {
  return {
    title: "Create Next App",
    description: "Generated by Ranjith",
  };
};
