import Carousal from "./components/Carousal/Carousal";
import Hero from "./components/Hero/Hero";
export default function Home() {
  return (
    <>
      <Carousal />
      <Hero />
    </>
  );
}

export const generateMetadata = () => {
  return {
    title: "Create Next App",
    description: "Generated by Ranjith",
  };
};
